### ISSUE TITLE
EJDB is LGPL

### ISSUE THREAD

**Issue by Type1J** [almightycouch/meteorpp#2]
EJDB is LGPL. This prevents use on closed systems. Please switch to a BSD or MIT licenced client side cache database.

**Comment by redrabbit** [comment]
LGPL does not prevent the use of this project in closed-sourced/proprietary systems per se.

Here's the three main obligations when you use software licensed under the LGPL:

* Your application should link EJDB as shared library.
* You must make the EJDB sources *– including modifications to the EJDB sources –* publicly available.
* You must enable users to build the EJDB sources, deploy the EJDB library and run the original application using the modified EJDB library.

Currently the provided `CMakeLists.txt` is configured to create a shared-library, the EJDB sources (including modifications) are available publicly on GitHub (see fork [here](https://github.com/almightycouch/ejdb/tree/meteorpp)) and the `README.md` should be enough to let users compile and deploy the modified EJDB version on any supported platform if they wish to. So you are pretty much covered here.

> Please switch to a BSD or MIT licenced client side cache database.

There aren't so many lightweight MongoDB databases written in C or C++ out their. If you find something that fits your needs, you can try to swap-out EJDB. I'm open to any kind of pull-requests.

**Comment by Type1J** [comment]
I didn't say closed source. I said closed systems.

I would like to use it on a cable box with an encrypted file system, but I had to go with a solution that isn't as desirable because of the LGPL use in this project.

I will switch to this library if EJDB switches their licence to MIT or BSD, or if you replace EJDB somehow.

Because our file system is encrypted, allowing someone to flip .so files out from inside of our sandbox would introduce instability and a major security hole.
