### ISSUE TITLE
ejdbqrymatch not declared (patch missing?)

### ISSUE THREAD

**Issue by Koerner** [almightycouch/meteorpp#3]
I tried to install meteorcpp, while running make I get the following error:
`../meteorpp/src/live_query.cpp: In member function ‘bool meteorpp::live_query::match(const object_t&)’:
../meteorpp/src/live_query.cpp:116:16: error: ‘ejdbqrymatch’ was not declared in this scope
         return ejdbqrymatch(std::shared_ptr<EJQ>(ejdbcreatequery2(_coll->_db.get(), bson_data(_selector.get())), ejdbquerydel).get(), collection::convert_to_bson(document).get());`

It seems like the patch of ejdb was not apllied, but I did apply it. What I did:

- Run  the installation without the patch -> failed
- deleted all build folders, apllied the patch in ejdb (`git apply ../master...almightycouch\:meteorpp.patch
`), cmake and make for ejdb and meteorcpp
- still the same error

Did I miss to clean something before appling the patch? It seems like the patch has no effect.

Thanks for any hint

**Comment by redrabbit** [comment]
The forked/patched EJDB branch is already available as a submodule. Be sure that you clone `meteorpp` with `--recursive` or if you already have cloned the repository run:

    git submodule update --init --recursive


See README.md for installation details:

> Installing EJDB is pretty easy as well as we provide the patched library as submodule.
>
>     cd ejdb/
>     mkdir build/
>     cd build/
>     cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../dist ../
>     make && make install
>     cd ../../
